soy mas pro que julian :v
CarolayMeza/TiendaOrganica pull request #6
Opened 2021-09-12 19:21 UTC by YordiColina

revisen  esto please  me avisan cualquier cosa

2021-09-12 19:22 UTC, CarolayMeza commented
hola yordis intentalo de nuevo

2021-09-12 19:24 UTC, RossyTobaria reviewed
Yordi: estamos en nivel 25% de github

2021-09-12 19:24 UTC, CarolayMeza requested changes

2021-09-12 19:24 UTC, CarolayMeza commented on yordi.txt
> +soy mas pro que julian
Utiliza mayuscula en Soy

2021-09-15 02:28 UTC, Julianfr23 commented on yordi.txt
> +soy mas pro que julian
No moleste :)

2021-09-16 00:12 UTC, closed without merging