Julian
CarolayMeza/TiendaOrganica pull request #9
Opened 2021-09-15 03:12 UTC by Julianfr23

Hola chicos esto es para actualizar el main. Aclaro solo van las modificaciones que hizo Carol al programa base, la base de datos no va ahi.

2021-09-15 03:14 UTC, YordiColina approved these changes
buen trabajo

2021-09-17 00:48 UTC, CarolayMeza requested changes
Por favor no borrar gitignore.
por favor no pon archivos binarios en git. por los imagines, usa un drive como AWS S3.

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +			if(usuario.equals("admininicial") && password.equals("admin123456")) {
Por favor usa archivos secretos y importa esta cadena de tu archivo secreto a tu gitignore.
.inv

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/.settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
No subas archivos de configuración por eclipse, ya que este codigo no lo necesitamos porque no es creado por nosotros, este solo es para la configuración de tomcat y configuración de eclipse.

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +				JOptionPane.showMessageDialog(null, "Bienvenido");
Este showMessageDialog es una parte de vista necesitamos separar lo que es del controlador con lo que pertenece a la vista

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +				JOptionPane.showMessageDialog(null, "Bienvenido");
veo muchas partes que están mezclando controlador y vista, por favor aplica este consejo con todo el código.

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +			}else if(usuario==Usuarios[0] && password==Usuarios[2]) {
este diseño no es limpio no usar Array por  usuario[1] o usuario [2], para guardar información en memoria, utiliza clase de datos para hacerlo

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +		String Rnombre,Rcorreo,Rcontrasenia;
por favor sigue la regla de como escribir nombres en Java 
nombreUsario por ejemplo.

y también, no necesitamos guardar espacio en codigo. Entonces, utiliza palabras enteras. no usar solo una letra como R, Que significa R?

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +			Usuarios[1]=Rcorreo;
este es un ejemplo en que este codigo no es flexible para cambiar. Que vamos a hacer si necesitamos dejar personas para no utilizar un campo de dato para hacer opcional? este linea de codigo va a tirar un error

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +			Usuarios[1]=Rcorreo;
usa classes
public class User {
(pon tu codigo especifico por usuario aqui)
}

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +				JOptionPane.showMessageDialog(null,"No Se Pudo Crear El Usuario");
este no es un mensaje de error suficiente

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +				response.sendRedirect("Login.jsp");
mira mejor ejemplos de reiniciar datos cuando ellos tienen la contraseña incorrecta.

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/java/Controlador/Control_login.java
> +			}
tambien, pon oportunidad para recrear su contraseña si se  le olvida x veces

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/webapp/Css/estilos.css
> +@media(min-width:768px)
ya probaste este configuración con tu celular? la mayoría de pagos en la red no es con una computadora. necesitas crear configuraciones mas responsables con célular o otros tamaños

2021-09-17 00:48 UTC, CarolayMeza commented on Intento_Login/src/main/webapp/Login.jsp
> +                <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
limpia este

2021-09-17 00:48 UTC, CarolayMeza commented on Tienda_Organica.sql
> +
lee los comentarios en la rama de Rossy.

2021-09-17 00:48 UTC, CarolayMeza commented on estilo/estilos.css
> +input[type="password"]{
consolidar tu archivos de style.css

2021-09-22 05:33 UTC, closed without merging